export const FETCH_AUTH_FULFILLED = 'FETCH_AUTH_FULFILLED';
export const FETCH_AUTH_REJECTED = 'FETCH_AUTH_REJECTED';
export const FETCH_LIST_EMPLOYEES = 'FETCH_LIST_EMPLOYEES';
export const FETCH_CURRENT = 'FETCH_CURRENT';
export const FETCH_LAST = 'FETCH_LAST';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_TOTAL = 'FETCH_TOTAL';
